Repository Pawelek99/feedbackTool, pull requests merged in 2020-05, with the labels that each got.

#3 Create main page
  .gitignore
  Readme.md
  index.js
  nodemon.json
  package-lock.json
  package.json
  routes/index.js
  routes/main.js
  routes/room.js
  styles/global/global.css
  styles/global/global.scss
  styles/main/main.css
  styles/main/main.scss
  styles/main/popup.css
  styles/main/popup.scss
  styles/room/room.css
  styles/room/room.scss
  views/main.ejs
  views/room.ejs
Labels: feature

#5 Create backend
  index.js
  package-lock.json
  package.json
  routes/api/data.js
  routes/api/index.js
  routes/index.js
  routes/main.js
Labels: feature

#8 Create room page
  styles/global/popup.css
  styles/global/popup.scss
  styles/main/popup.css
  styles/room/room.css
  styles/room/room.scss
  views/main.ejs
  views/room.ejs
Labels: feature

#7 Create '/' page
  index.js
  public/notFound.svg
  public/wait.svg
  routes/api/index.js
  routes/index.js
  routes/main.js
  routes/notFound.js
  routes/room.js
  routes/root.js
  styles/global/global.css
  styles/global/global.scss
  styles/main/main.css
  styles/main/main.scss
  styles/notFound/notFound.css
  styles/notFound/notFound.scss
  styles/room/room.css
  styles/room/room.scss
  styles/root/root.css
  styles/root/root.scss
  views/notFound.ejs
  views/room.ejs
  views/root.ejs
Labels: feature

#12 Connect popups with backend
  index.js
  routes/api/data.js
  routes/api/index.js
  views/main.ejs
  views/room.ejs
Labels: feature

#14 Create freeSession and generateId buttons
  .gitignore
  index.js
  package-lock.json
  package.json
  public/refresh.js
  routes/add.js
  routes/api/data.js
  routes/api/index.js
  routes/index.js
  routes/main.js
  routes/room.js
  routes/root.js
  styles/add/add.css
  styles/add/add.scss
  styles/global/global.css
  styles/global/global.scss
  styles/global/popup.css
  styles/main/main.css
  styles/notFound/notFound.css
  styles/notFound/notFound.scss
  styles/room/room.css
  styles/root/root.css
  styles/root/root.scss
  views/add.ejs
  views/main.ejs
  views/room.ejs
Labels: feature

#16 Possibility to remove rooms
  routes/api/index.js
  styles/main/main.css
  styles/main/main.scss
  styles/notFound/notFound.css
  views/main.ejs
  views/room.ejs
Labels: feature

#18 Possibility to remove rooms
  views/room.ejs
Labels: feature

#19 bugs
  views/room.ejs
Labels: bug

#20 bugs
  package.json
  styles/add/add.css
  styles/global/global.css
  styles/global/popup.css
  styles/main/main.css
  styles/notFound/notFound.css
  styles/room/room.css
  styles/root/root.css
  styles/root/root.scss
  views/add.ejs
Labels: bug

#22 Small tweaks and fixed
  index.js
  public/add.svg
  public/alone.svg
  routes/api/data.js
  routes/api/index.js
  routes/main.js
  routes/root.js
  styles/add/add.css
  styles/add/add.scss
  styles/global/global.css
  styles/global/global.scss
  styles/global/popup.css
  styles/main/main.css
  styles/main/main.scss
  styles/notFound/notFound.css
  styles/room/room.css
  styles/room/room.scss
  styles/root/root.css
  styles/root/root.scss
  views/main.ejs
  views/room.ejs
  views/root.ejs
Labels: enhancement
